eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
uris:
  payment-service: http://payment-service/payment/processPayment
  order-service: http://order-service/order/placeOrder
message: This message came from the config server
